### ISSUE TITLE
Failure to access with new amc x824v control panels

### ISSUE THREAD

**Issue by pippo8683** [vermut/ha_amc_alarm#4]
Good morning, the problem is that the new x824v control unit does not access because when accessing the new control unit it also asks you for the password for arming and disarming the system. I hope you fix it soon because you did a great job congratulations

**Comment by vermut** [comment]
Thanks, I'm trying my best.

For the passwords and x824v you will need to teach me, because I've never seen it. 

First simple question - does it work with AMC Plus mobile app? If yes - can you send me a couple of screenshots how it works when arming/disarming?

Second - did you install AMC Alarm in HomeAssistant already? If yes - what is happening when you arm disarm?

Pavels

**Comment by vermut** [comment]
It seems like an phone related password, like a pin that you set up when installing phone app.

Have you tried running the HomeAssistant integration?

**Comment by pippo8683** [comment]
Search for the anti-theft password

Il lun 3 giu 2024, 17:42 Pavel Veretennikov ***@***.***> ha
scritto:

**Comment by vermut** [comment]
Show me a screenshot from HomeAssistant with error

**Comment by pippo8683** [comment]
Ecco

Il lun 3 giu 2024, 17:48 Coccolone Esposito ***@***.***> ha
scritto:

**Comment by vermut** [comment]
no screenshots yet

**Comment by pippo8683** [comment]
Il lun 3 giu 2024, 18:16 Pavel Veretennikov ***@***.***> ha
scritto:

**Comment by pippo8683** [comment]
I sent 2

Il lun 3 giu 2024, 18:16 Coccolone Esposito ***@***.***> ha
scritto:

**Comment by vermut** [comment]
do it from PC, I think it doesn't work from the phone

**Comment by pippo8683** [comment]
The same thing doesn't come out even with the PC, but I repeat with the new
control panels outside email, password, id, user, password it also asks for
the system code so it doesn't let you in This is done with x824 v4.1 panels

Il lun 3 giu 2024, 18:20 Pavel Veretennikov ***@***.***> ha
scritto:

**Comment by vermut** [comment]
I still don't see any screenshots. Ok, explain me verbally, where does it break:

- can you install AMC Alarm in HomeAssistant? (yes/no)
- can you add AMC Alarm integration (enter user pass UID)? (yes/no)
- can you see zone/group/area entities in HomeAssistant? (yes/no)

**Comment by pippo8683** [comment]
Sei italiano possiamo parlare a voce

Il lun 3 giu 2024, 18:39 Pavel Veretennikov ***@***.***> ha
scritto:

**Comment by vermut** [comment]
No, I'm Latvian, I just happen to have AMC central at home.

**Comment by pippo8683** [comment]
![WhatsApp Image 2024-06-03 at 18 49 52](https://github.com/vermut/ha_amc_alarm/assets/111242393/7d5640fc-d261-415f-a426-f4a73f5f80a7)

**Comment by pippo8683** [comment]
If you saw the video I sent you this morning you can see that at the end of the video it searches for an additional code. that code and the anti-theft one only do this with the new x824v 4.10 control units

**Comment by vermut** [comment]
Need to see what's going on inside:
- In you AMC Integration Home Assistant page enable "Debug logging"
- try going through setup again (adding central). Input all values correctly.
- In you AMC Integration Home Assistant page DISABLE "Debug logging"
- It will ask to download a file. 
- Edit out passwords and send it to `vermut+amc@pm.me`

**Comment by pippo8683** [comment]
How do I turn on debug logging if it won't let me log in?

**Comment by vermut** [comment]
Indeed. Try enabling debug logging by [editing the configuration.yaml](https://www.home-assistant.io/integrations/logger/)
```
# Example configuration.yaml entry
logger:
  logs:
    custom_components.amc_alarm: debug
```
and them get those records from system log.


Or change you password to temporary one and send me the config - I'll just try it myself. It will be the fastest and probably most effective way, but... this is your home alarm. I take no liability to anything that can happen.

**Comment by pippo8683** [comment]
I sent you the file

**Comment by vermut** [comment]
Yeah, I see, it's acting weird. Let me try it.

**Comment by pippo8683** [comment]
in my opinion in the access you have to add the two access versions one as is for the x824 3.73 versions and another for the x824v 4.10 versions where the last one requires an additional code to access

**Comment by vermut** [comment]
No, the code is purely on the phone. But the central is indeed different, it has `"amcProtoVer": 2`. I've only seen V1, so let me add code to support it.

**Comment by vermut** [comment]
Try version 1.0.0?

**Comment by pippo8683** [comment]
great job, everything sorted out, congratulations

**Comment by pippo8683** [comment]
Hello good morning, please satisfy my curiosity, could you do itHello good
morning, please satisfy my curiosity, would you be able to do this with
another video surveillance app?

Il lun 3 giu 2024, 23:33 Pavel Veretennikov ***@***.***> ha
scritto:

**Comment by vermut** [comment]
Well, I know Home Assistant part already and assume that it will be similar. So the problem would be figuring out the protocol. 
If you provide me access to actual working app I can take a look to see how hard it might be.

**Comment by pippo8683** [comment]
Hi, the app is on the store and is called btvision access and
***@***.*** Pass Riggiola86
Il mar 4 giu 2024, 11:16 Pavel Veretennikov ***@***.***> ha
scritto:

**Comment by Eskander** [comment]
Hello, thank you for the great work!
I confirm that with the newest update, the integration also works with X64V/4.20 now.
