### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by GitWally** [vermut/ha_amc_alarm#8]
Hello,
first of all let me thank you for this integration: I was really hoping to find it!

I have a X864/4.10 but, may be because of my fault, I'm not able to log-in.
In the following picture the correspondence of fields from the app and the integration, as per my understanding

![image](https://github.com/user-attachments/assets/341cef59-efd4-49d5-a82e-35c4df9a98b9)

But as you can see it ends with "Invalid login": I'm trying from PC, not from HA Companion App.
May be it depends on the fact I have symbols in my very complicated password?
These are the symbols I use

`'"\!``

Let me know if you need some logs (and where I am suppose to take them from, because I found nothing ... )
Many thanks in advance

**Comment by vermut** [comment]
Very good picture. I might steal it for documentation :)


Logs are in usual HA logs section. You can enable debug logs in the integration and then check the logs or it will offer to download bundle when you disable it back.

Alternative option is to share the credentials with me (vermut+gitlab@pm.me) and them change them. But if we are talking changing creds, you can change them first to simple password and check if it is the reason.

**Comment by GitWally** [comment]
Hello @vermut 
glad to know you like the picture: you can take it, for sure (my very little contribution!)

About logs: I tryied (in the wrong way, for sure) to find logs in Settings > System > Log> Home Assistant Core > Show full logs.
But found nothing.
I tried also to enable logs in the integration ... but cannot because it's not yet configured, disabled or ignored.

From HACS I cannot see how to enable logs:

![image](https://github.com/user-attachments/assets/0b964e5b-5fa2-4b51-bac1-402cc9078aa0)

I will try to reset password, because the AMC Password cannot contain special chars (and it does not), but the webapp password does! So I will try to reset (or create a new user) with easier one and let you know!
Thanks

**Comment by GitWally** [comment]
Funny ... I re-set my WebApp Passwor (now it contains just - and _ as special character.
But the answer from the integration is: **User login is fine but can't find AMC Central**

It's not a typo for sure: I copy and paste!

![image](https://github.com/user-attachments/assets/c5b332eb-d7f3-4921-8417-afb0ee79d923)

**Comment by GitWally** [comment]
Found the solution: 

1. kick out the House from the App before logging in the Integration.
2. log in the WebApp and re-associate the House AMC Central

**Comment by vermut** [comment]
So it sounds like a special char escape problem in a password?
